In [1]:
import torch

In [6]:
torch.tensor(10)

tensor(10)

In [11]:
torch.tensor([10])

tensor([10])

In [15]:
a = torch.tensor(10)
b = torch.tensor([10])

In [23]:
a.float()

tensor(10.)

In [20]:
b.long()

torch.int64

In [18]:
import numpy as np

arr = np.array(10)
torch.from_numpy(arr)

tensor(10, dtype=torch.int32)

In [22]:
torch.ones([3, 3, 2])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [26]:
torch.zeros((3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
torch.rand((3, 3))

tensor([[0.3610, 0.5362, 0.9311],
        [0.5934, 0.9721, 0.3078],
        [0.9104, 0.9096, 0.0494]])

In [29]:
torch.randn((3, 3))

tensor([[-0.7450, -0.7312,  0.1308],
        [ 0.9646,  0.3303, -1.4382],
        [ 1.0630, -0.1347, -0.8625]])