In [1]:
import torch

In [6]:
torch.tensor(10)

tensor(10)

In [11]:
torch.tensor([10])

tensor([10])

In [15]:
a = torch.tensor(10)
b = torch.tensor([10])

In [23]:
a.float()

tensor(10.)

In [20]:
b.long()

torch.int64

In [18]:
import numpy as np

arr = np.array(10)
torch.from_numpy(arr)

tensor(10, dtype=torch.int32)

In [22]:
torch.ones([3, 3, 2])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [26]:
torch.zeros((3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
torch.rand((3, 3))

tensor([[0.3610, 0.5362, 0.9311],
        [0.5934, 0.9721, 0.3078],
        [0.9104, 0.9096, 0.0494]])

In [29]:
torch.randn((3, 3))

tensor([[-0.7450, -0.7312,  0.1308],
        [ 0.9646,  0.3303, -1.4382],
        [ 1.0630, -0.1347, -0.8625]])

In [5]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([2, 3, 1, 2])

x + y, x - y, x * y, x / y

(tensor([3, 5, 4, 6]),
 tensor([-1, -1,  2,  2]),
 tensor([2, 6, 3, 8]),
 tensor([0.5000, 0.6667, 3.0000, 2.0000]))

In [6]:
x ** y

tensor([ 1,  8,  3, 16])

In [7]:
torch.add(x, y), torch.sub(x, y), torch.mul(x, y), torch.div(x, y), torch.pow(x, y)

(tensor([3, 5, 4, 6]),
 tensor([-1, -1,  2,  2]),
 tensor([2, 6, 3, 8]),
 tensor([0.5000, 0.6667, 3.0000, 2.0000]),
 tensor([ 1,  8,  3, 16]))

In [8]:
x = torch.randn((3, 2))
y = torch.randn((2, 3))

torch.matmul(x, y)

tensor([[-0.5539,  0.6074, -0.5611],
        [-0.0451, -0.1483, -0.2463],
        [-1.3173,  1.8635, -0.9092]])

In [9]:
x.shape

torch.Size([3, 2])

In [10]:
x.reshape((2, 3))

tensor([[ 1.3438,  0.1454,  1.4573],
        [-0.3150,  0.3388,  1.0383]])

In [11]:
x.view((1, 6))

tensor([[ 1.3438,  0.1454,  1.4573, -0.3150,  0.3388,  1.0383]])

In [2]:
x = torch.randn((3, 2, 4))

In [4]:
x.transpose(0, 1).shape

torch.Size([2, 3, 4])

In [6]:
x.permute((2, 1, 0)).shape

torch.Size([4, 2, 3])

In [7]:
x = torch.randn((3, 1, 5))

In [13]:
x.unsqueeze(-1).shape

torch.Size([3, 1, 5, 1])

In [14]:
x[0]

tensor([[-0.8247,  2.2122,  0.4273,  1.0935, -1.2773]])

In [15]:
x[:, 0]

tensor([[-0.8247,  2.2122,  0.4273,  1.0935, -1.2773],
        [-0.7823, -0.7452, -1.5099, -1.5247, -1.6767],
        [ 1.5353,  0.1188,  0.6579,  1.5378, -1.8785]])